### ISSUE TITLE
3.0 final release

### ISSUE THREAD

**Issue by arkaitzgarro** [arkaitzgarro/elastic-apm-laravel#108]
Looks like all new functionality and necessary changes to accommodate the new agent are complete, and we can release the final 3.0 version. This is what I will include in the release notes, please let me know if I am missing something:

**Features**
- Added a new collector for artisan commands (https://github.com/arkaitzgarro/elastic-apm-laravel/pull/76).
- Added a new collector for scheduled tasks (https://github.com/arkaitzgarro/elastic-apm-laravel/pull/76).

**Fixes**
- Correctly filter out events based on global `APM_MAXTRACEITEMS` value (https://github.com/arkaitzgarro/elastic-apm-laravel/pull/89)
- Reset EventDataCollectors and add Metadata after each send (https://github.com/arkaitzgarro/elastic-apm-laravel/pull/77)

**BREAKING CHANGES**
- Dropped support for Laravel 5 (https://github.com/arkaitzgarro/elastic-apm-laravel/pull/106)
- Removed Guzzle http client adapter (https://github.com/arkaitzgarro/elastic-apm-laravel/pull/95). This allows users to chose their own HTTP client implementation, but it also means that now you are responsible of installing a new dependency compatible with PSR18 if don't have a client already installed.
- Replaced underlying PHP agent `philkra/elastic-apm-php-agent` with `nipwaayoni/elastic-apm-php-agent` (https://github.com/arkaitzgarro/elastic-apm-laravel/pull/72). The previous agent is not under maintenance anymore, and the author [agreed on transfering the ownership](https://github.com/philkra/elastic-apm-php-agent/issues/136#issuecomment-621883404) to an [organization](https://github.com/nipwaayoni/elastic-apm-php-agent). This change should be transparent for most the users, unless you were extending the `Agent` class. In this case, refer to the [agent documentation](https://github.com/nipwaayoni/elastic-apm-php-agent/blob/master/docs/agent.md#creating-an-agent) and the new way to create an instance [in this package](https://github.com/arkaitzgarro/elastic-apm-laravel/blob/master/src/ServiceProvider.php#L105L115).

@countless-integers @dstepe is there anything else you would like to add?

**Comment by dstepe** [comment]
I think the removal of Guzzle is a BC for most people. It fixes a specific use case, but I don't see that it was previously reported, so the release notes should probably point out what most people will experience, a need to add a new dependency as part of the upgrade.

The only other thing that comes to mind relates to the jobCollector. If that was present in the previous release, would it not have exhibited the send failures reported in #57 and fixed in #77? It that was not in the previous release, then it should be added as a new feature.

**Comment by dstepe** [comment]
It occurred to me that the 1.x branch we are proposing to support Laravel `^5.5 <6.0` will introduce breaking changes in what should be a minor release (following semver). What do you think about release that as 2.x and moving these release to 3.x? The 2.x line will start the new Agent and provide pre-Laravel 6 support (to a reasonable extent) while the 3.x line will move the project features forward and provide Laravel 6+ support. That will prevent surprises for your current users and make it easier to communicate what release to use.

**Comment by arkaitzgarro** [comment]
> I think the removal of Guzzle is a BC for most people. It fixes a specific use case, but I don't see that it was previously reported, so the release notes should probably point out what most people will experience, a need to add a new dependency as part of the upgrade.

Yes, this is a good point, I will make it part of the release note. Thanks.

> The only other thing that comes to mind relates to the jobCollector. If that was present in the previous release, would it not have exhibited the send failures reported in #57 and fixed in #77? It that was not in the previous release, then it should be added as a new feature.

Correct, this is something that we also fixed 👍

**Comment by arkaitzgarro** [comment]
> It occurred to me that the 1.x branch we are proposing to support Laravel `^5.5 <6.0` will introduce breaking changes in what should be a minor release (following semver). What do you think about release that as 2.x and moving these release to 3.x? The 2.x line will start the new Agent and provide pre-Laravel 6 support (to a reasonable extent) while the 3.x line will move the project features forward and provide Laravel 6+ support. That will prevent surprises for your current users and make it easier to communicate what release to use.

I agree. I will release 3.0 for now, and wait until we make sure 2.x branch work as expected on L5.5 applications.

**Comment by dstepe** [comment]
I'm working on what is now the 1.x branch. I may not be able to complete it today unfortunately, but hopefully tomorrow.

**Comment by arkaitzgarro** [comment]
> I'm working on what is now the 1.x branch. I may not be able to complete it today unfortunately, but hopefully tomorrow.

You mean 2.x branch right? I will create a 3.0 release for L6 support and 2.0 for L5.5. Latest changes are be available on 2.x branch already.

**Comment by dstepe** [comment]
Well, yes. It was still named 1.x when I started. I'll get caught up. :)

**Comment by arkaitzgarro** [comment]
`v3.0` has been released 🎉
