### ISSUE TITLE
2.0 release

### ISSUE THREAD

**Issue by dstepe** [arkaitzgarro/elastic-apm-laravel#115]
Will you make an actual 2.0 release from the 2.x branch? Is there anything outstanding for that I could help with?

**Comment by arkaitzgarro** [comment]
If everything is ok on your side, I can create the release right now.

## Features
- Added a new collector for artisan commands (https://github.com/arkaitzgarro/elastic-apm-laravel/pull/76).

## Fixes
- Correctly filter out events based on global `APM_MAXTRACEITEMS` value (https://github.com/arkaitzgarro/elastic-apm-laravel/pull/89)
- Reset EventDataCollectors and add Metadata after each send (https://github.com/arkaitzgarro/elastic-apm-laravel/pull/77)

## BREAKING CHANGES
- Dropped support for Laravel >=6 (https://github.com/arkaitzgarro/elastic-apm-laravel/pull/112)
- Removed Guzzle http client adapter (https://github.com/arkaitzgarro/elastic-apm-laravel/pull/95). This allows users to chose their own HTTP client implementation, but it also means that now you are responsible of installing a new dependency compatible with PSR18 if don't have a client already installed.
- Replaced underlying PHP agent `philkra/elastic-apm-php-agent` with `nipwaayoni/elastic-apm-php-agent` (https://github.com/arkaitzgarro/elastic-apm-laravel/pull/72). The previous agent is not under maintenance anymore, and the author [agreed on transfering the ownership](https://github.com/philkra/elastic-apm-php-agent/issues/136#issuecomment-621883404) to an [organization](https://github.com/nipwaayoni/elastic-apm-php-agent). This change should be transparent for most the users, unless you were extending the `Agent` class. In this case, refer to the [agent documentation](https://github.com/nipwaayoni/elastic-apm-php-agent/blob/master/docs/agent.md#creating-an-agent) and the new way to create an instance [in this package](https://github.com/arkaitzgarro/elastic-apm-laravel/blob/master/src/ServiceProvider.php#L105L115).

**Comment by dstepe** [comment]
Looks good to me. I've used the branch ref in one project so far without any issues. Thanks!

**Comment by arkaitzgarro** [comment]
Done! https://github.com/arkaitzgarro/elastic-apm-laravel/releases/tag/v2.0
