### ISSUE TITLE
Remove composer.lock

### ISSUE THREAD

**Issue by cykirsch** [arkaitzgarro/elastic-apm-laravel#126]
As of now I haven't experienced any issues with this, but I noticed the conversation https://github.com/arkaitzgarro/elastic-apm-laravel/pull/95#issuecomment-712225362.

I'm curious, with the release of composer version 2, do you still have the issues with circleci?

**Comment by arkaitzgarro** [comment]
Hey @cykirsch,

`composer.lock` file is not part of the repository anymore! It was removed when we moved from circleci to GitHub actions, as they offer a much better way to configure a matrix of PHP/Laravel jobs.

And yes, Composer version 2 is a huge improvement when it comes to performance, both in memory usage and installation speed, as you can see in [this PR](https://github.com/arkaitzgarro/elastic-apm-laravel/pull/113).
