### ISSUE TITLE
Extending RecordTransaction middleware 

### ISSUE THREAD

**Issue by rogercbe** [arkaitzgarro/elastic-apm-laravel#132]
Hello, I was wondering which would be the most appropiate way to extend the RecordTransaction middleware. The main concern I'm facing is that I want to record additional information from each request, for example body params, aswell as more information about the user and session. 

Would happily work on a PR if we can agree on a solution!

Thank you!

**Comment by arkaitzgarro** [comment]
Hi @rogercbe,

One way to achieve sending extra information to the current transactions is using the `ApmAgent` facade. You could do the following in one of your existing middlewares, or create a new for this purpose.

```php
<?php

namespace App\Http\Middleware\Auth;

use Closure;
use AG\ElasticApmLaravel\Facades\ApmAgent;

class MyMiddleware
{
    public function handle($request, Closure $next)
    {
        $response = $next($request);
        
        try {
            ApmAgent::getCurrentTransaction()->setCustomContext([
                'body' => $request->all(),
                ...
            ]);
        } catch (Exception $e) {
            // The connection with Elastic might fail, better be safe than sorry
        }

        return $response;
    }
}

```

**Comment by rogercbe** [comment]
Thank you, working perfectly with this approach. For anyone having problems with the mappings on APM indexes I followed this thread: https://discuss.elastic.co/t/apm-index-not-refreshing/195884/5

Refreshing the index alone didn't make the trick and the fields could'nt be used for search/operations
