### ISSUE TITLE
ELASTIC_APM_ environment variables not available to the Agent when the Laravel config is cached

### ISSUE THREAD

**Issue by dstepe** [arkaitzgarro/elastic-apm-laravel#134]
When the Laravel application configuration is cached (`artisan config:cache`) the `.env` file is not parsed and no environment variables are set. As a consequence, the underlying `Agent` does not have the expected `ELASTIC_APM_` configuration variables and fails to start.

The `Agent` is following the general practice of other APM agent implementations of configuration through environment variables. The configuration can also be provided as an array, as was previously done. While we wanted to avoid a one-to-one mapping of values through this package to the `Agent`, that may be the only solution to this caching issue.

**Comment by arkaitzgarro** [comment]
Thanks for the investigation @dstepe. We do actually cache the configuration as a part of the deployment process, but never updated the environment variables to be prefixed with `ELASTIC_APM_`. That can also be the reason we didn't realise about the issue.

**Comment by dstepe** [comment]
Apologies for not following up on this sooner. When considering the Laravel configuration cache behavior, I don't see how it will be practical to defer library configuration in the way I wanted. This isn't an issue with the Library, and the agent package will continue to support the environment variables to be consistent with other agent implementations. This is simply a consequence of how Laravel configuration caching works.

I'm working on fix which will utilize all of the `ELASTIC_APM` environment variables in the config.
