### ISSUE TITLE
Error when composer require 

### ISSUE THREAD

**Issue by ulisest** [arkaitzgarro/elastic-apm-laravel#138]
this is how this packege is on my composer.json "arkaitzgarro/elastic-apm-laravel": "^3.0",
php version PHP 7.4.13 (cli)
Composer version 2.0.8 2020-12-03 17:20:38

When running composer required or composer update this error is showing
> @php artisan package:discover

   TypeError

  Return value of AG\ElasticApmLaravel\ServiceProvider::getAppConfig() must be of the type array, null returned

  at ....\vendor\arkaitzgarro\elastic-apm-laravel\src\ServiceProvider.php:227
    223|         if ($this->app->bound(VersionResolver::class)) {
    224|             $config['appVersion'] = $this->app->make(VersionResolver::class)->getVersion();
    225|         }
    226|
  > 227|         return $config;
    228|     }
    229|
    230|     private function isAgentDisabled(): bool
    231|     {

  1   ....\vendor\arkaitzgarro\elastic-apm-laravel\src\ServiceProvider.php:214
      AG\ElasticApmLaravel\ServiceProvider::getAppConfig()

  2  ....\vendor\arkaitzgarro\elastic-apm-laravel\src\ServiceProvider.php:105
      AG\ElasticApmLaravel\ServiceProvider::getAgentConfig()

   TypeError

  Return value of AG\ElasticApmLaravel\ServiceProvider::getAppConfig() must be of the type array, null returned

  at ....\vendor\arkaitzgarro\elastic-apm-laravel\src\ServiceProvider.php:227
    223|         if ($this->app->bound(VersionResolver::class)) {
    224|             $config['appVersion'] = $this->app->make(VersionResolver::class)->getVersion();
    225|         }
  > 227|         return $config;
    229|
    231|     {

  1   ....\vendor\arkaitzgarro\elastic-apm-laravel\src\ServiceProvider.php:214
      AG\ElasticApmLaravel\ServiceProvider::getAppConfig()

  2   ....\vendor\arkaitzgarro\elastic-apm-laravel\src\ServiceProvider.php:105
      AG\ElasticApmLaravel\ServiceProvider::getAgentConfig()
Script @php artisan package:discover handling the post-autoload-dump event returned with error code 1

**Comment by dstepe** [comment]
Was this package previously installed in your project and you upgrading it? Do you have an existing `config/elastic-apm-laravel.php` file in your project? The only way that the error you're getting should happen is if the configuration `app` key is not an array:

```
$config = config('elastic-apm-laravel.app');
```

**Comment by ulisest** [comment]
Its firts time i use this package, i was migrating from another apm package. This is the name "elastic-apm-laravel.php"? mine has "elastic-apm.php" that must be, but it was weird, on one computer all install without problem and on another was throwing this error. I will check with the name to see if everything works fine. Thanks

**Comment by dstepe** [comment]
The problem you describe could be caused by a configuration problem. If the file name doesn't match the one from this package then I wouldn't expect that to be the problem. It's certainly a good idea to completely clean out the previous package, including it's configuration, before installing this one.
