### ISSUE TITLE
Queueig requests to elasticsearch (sending in background)

### ISSUE THREAD

**Issue by rogercbe** [arkaitzgarro/elastic-apm-laravel#140]
Hello there, 

Is there a way to queue the transaction requests to elasticsearch? I've been digging into the source and haven't found a way to do so by myself. If I'm not mistaken, the request is sync and blocking, meaning that if there is a problem with that request and there is an error it would be an exception that would be catched, but what about the situations where there is no error because the server does not respond? 

I think it would be quite interesting to configure if the transactions are sent async instead, for example in case that the connection with elasticsearch is unstable because the elastic is down or it timeouts. In this scenario the whole application would suffer that degradation on both http requests and cli jobs. Actually the jobs will get stuck and stop processing if job timeout option is not set. I can provide an example to reproduce this scenario.

Is there another way to handle those cases where the connection with elastic is down? Besides setting to false the APM_ACTIVE flag.

Maybe I'm missing something in my configuration that makes it very sensible to elasticsearch server being always accessible but if you find it interesting I could work on a PR to include queueing those requests so they can work on background and fail independently of the application flow.

Thank you!

**Comment by dstepe** [comment]
This is really a concern for the [APM Agent](https://github.com/nipwaayoni/elastic-apm-php-agent) package which is used to send the events. I did look into making the send to APM an async call, but that's not a straightforward as I had thought it would be. See this [old PR](https://github.com/nipwaayoni/elastic-apm-php-agent/pull/56) and the link to discussion on the Guzzle project about the need to [implement an event loop](https://github.com/guzzle/guzzle/issues/1127) for that to work.

My hope is that the [official APM PHP Agent](https://github.com/elastic/apm-agent-php) will bring some major improvements.

In the meantime, this package defers sending the collected event data to APM until after the response has been sent to the client. This at least prevents connection issues from impacting the application's response. Running from the CLI is different, of course. 

You can mange the http client used by the agent, though, which would give you the ability to set a shorter timeout. For example, in your `AppServiceProvider::register()` method:

```
$this->app->bind(\AG\ElasticApmLaravelAgentBuilder::class, function () {
    $builder = new \AG\ElasticApmLaravelAgentBuilder();

    $builder->withHttpClient(new \Http\Adapter\Guzzle6\Client(new Client(['timeout' => 3.0])));

    return $builder;
});
```

**Comment by arkaitzgarro** [comment]
Even if we send requests after the response is sent to the client, indeed the request to APM is sync and blocking. We had an issue today were APM server was not responding properly, making our application unstable. @rogercbe did you try the solution proposed by @dstepe to override the http client?

**Comment by countless-integers** [comment]
> \AG\ElasticApmLaravelAgentBuilder

You meant `\AG\ElasticApmLaravel\AgentBuilder`, right @dstepe?

Ok, for completeness we came up with this:

```php
$this->app->bind(\AG\ElasticApmLaravel\AgentBuilder::class, function () {
    return (new \AG\ElasticApmLaravel\AgentBuilder())
        ->withHttpClient(\Http\Adapter\Guzzle6\Client::createWithConfig(['timeout' => 3.0]));
});
```

**Comment by dstepe** [comment]
@countless-integers Yes, I'm sure that's what I meant. I can't explain where that `\` went. Apologies.

**Comment by arkaitzgarro** [comment]
@rogercbe please try the solution above, it worked for us. I'm closing the issue since it is not related to this package and we have a workaround for it.
