### ISSUE TITLE
Oficial APM Php Agent

### ISSUE THREAD

**Issue by rmundel** [arkaitzgarro/elastic-apm-laravel#142]
Hey!

Now that the Oficial PHP APM Agent is released, there's any plans to implement it over the current dependency?

Great work on this btw.

**Comment by arkaitzgarro** [comment]
Hi @rmundel,

If I understand correctly, the oficial Elastic agent is installed as a PHP extension, not as a dependency via Composer. And it seems to support Laravel ourt of the box, so I will say that at some point, it could even deprecate this package.

https://www.elastic.co/blog/elastic-apm-php-agent-1-0-released

I don't think there's anything we can do about it in this package.
