### ISSUE TITLE
Did not collect data from Api routes

### ISSUE THREAD

**Issue by rabinhod** [arkaitzgarro/elastic-apm-laravel#149]
Hi
How enable collect data from Api routes ?
right now it's collect data from web.php routes and work fine.

**Comment by arkaitzgarro** [comment]
We [prepend the middleware](https://github.com/arkaitzgarro/elastic-apm-laravel/blob/master/src/ServiceProvider.php#L132) without taking any group into consideration, it should work for every request.

Please review your configuration. Registering the [middleware](https://github.com/arkaitzgarro/elastic-apm-laravel/blob/f64226e66f4b6288170c374ad296aba64713d3f3/src/Middleware/RecordTransaction.php#L27) manually for your group could work, but I never tried.
