### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by jalithakanchana** [arkaitzgarro/elastic-apm-laravel#151]
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/38877968/135820165-55964709-466f-4f3f-a8ad-e4b64ccc3d94.png">

**Comment by arkaitzgarro** [comment]
The minimum required PHP version is 7.3, you are using 7.2. Please upgrade your version.

**Comment by jalithakanchana** [comment]
<img width="1216" alt="image" src="https://user-images.githubusercontent.com/38877968/136504563-e8e4e6e8-3a81-43bc-8994-9c1ac13d7da9.png">
