### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by jalithakanchana** [arkaitzgarro/elastic-apm-laravel#152]
<img width="1216" alt="image" src="https://user-images.githubusercontent.com/38877968/136504727-4dc40063-ebb8-4926-98fb-e84ccc53186d.png">

**Comment by arkaitzgarro** [comment]
Could you try `composer require arkaitzgarro/elastic-apm-laravel --no-scripts`?

**Comment by ivus84** [comment]
hello @arkaitzgarro , i had the same issue and the installation seems to be solved by using --no-scripts. 
btw the component makes php artisan config:cache command fail

`root@ip-172-26-2-29:/var/www/******#` php artisan config:cache

   TypeError 

  Return value of AG\ElasticApmLaravel\ServiceProvider::getAppConfig() must be of the type array, null re
turned

  at vendor/arkaitzgarro/elastic-apm-laravel/src/ServiceProvider.php:231
    227▕         if ($this->app->bound(VersionResolver::class)) {
    228▕             $config['appVersion'] = $this->app->make(VersionResolver::class)->getVersion();
    229▕         }
    230▕ 
  ➜ 231▕         return $config;
    232▕     }
    233▕ 
    234▕     private function isAgentDisabled(): bool
    235▕     {

can u please find a solid solution ? 
regards
I

**Comment by ivus84** [comment]
hello ,  any news about this ?

**Comment by arkaitzgarro** [comment]
Can you try publishing the configuration file, and clearing the cache after?

```
php artisan vendor:publish --tag=config
```

**Comment by ivus84** [comment]
running the command makes the "compiler" fail again. for the moment, I manually copied into the config folder the elastic-apm-laravel.php file, THEN I installed the plugin. doing this way seems to work. I hope it will help, but i guess there is room for improvement. regards. I

**Comment by arkaitzgarro** [comment]
Thanks for letting us know. We'll investigate further if it keeps happening.

**Comment by amrishkakadiya** [comment]
Try with deleting app/bootstrap/cache and try again, This solved my issue.
