### ISSUE TITLE
Laravel 9?

### ISSUE THREAD

**Issue by afiqiqmal** [arkaitzgarro/elastic-apm-laravel#156]
Any plan to upgrade to Laravel 9?

**Comment by arkaitzgarro** [comment]
No plans yet. Di you try installing the package already? Any feedback you can share already?

**Comment by afiqiqmal** [comment]
```
 Problem 1
    - arkaitzgarro/elastic-apm-laravel[v3.0-RC1, ..., v3.0.8] require illuminate/database ^6 || ^7 || ^8 -> found illuminate/database[v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev] but these were not loaded, likely because it conflicts with another require.
    - Root composer.json requires arkaitzgarro/elastic-apm-laravel ^3.0 -> satisfiable by arkaitzgarro/elastic-apm-laravel[v3.0-RC1, ..., v3.0.8].

You can also try re-running composer require with an explicit version constraint, e.g. "composer require arkaitzgarro/elastic-apm-laravel:*" to figure out if any version is installable, or "composer require arkaitzgarro/elastic-apm-laravel:^2.1" if you know which you need.
```

I think its required to include Illuminate 9

**Comment by countless-integers** [comment]
L9 also requires [PHP 8+](https://github.com/laravel/framework/blob/9.x/composer.json#L18) (ditto for components, e.g. [database](https://github.com/illuminate/database/blob/9.x/composer.json#L18)) where's we [require 7.3+](https://github.com/arkaitzgarro/elastic-apm-laravel/blob/master/composer.json#L17), so we'd need to bump PHP requirement along with all else.

**Comment by jplata** [comment]
@arkaitzgarro Is the PR for Laravel 9 done/safe to pull-in? Would love to get upgraded. Thanks.

https://github.com/arkaitzgarro/elastic-apm-laravel/pull/157

**Comment by arkaitzgarro** [comment]
> @arkaitzgarro Is the PR for Laravel 9 done/safe to pull-in? Would love to get upgraded. Thanks.
> 
> #157

Hey @jplata,

I managed to make the unit tests pass in the L9 branch, but I don't have any Laravel application where I could test the package. If I create a RC, would you be able to give it a try?

**Comment by jplata** [comment]
That would be great to try out, thanks.

**Comment by arkaitzgarro** [comment]
@jplata I created a [BETA tag](https://github.com/arkaitzgarro/elastic-apm-laravel/releases/tag/v4.0.0-BETA), please give it a try and let me know if it works 🤞

**Comment by snake-py** [comment]
@jplata What is the stand on this?

**Comment by snake-py** [comment]
So we tried the BETA tag and it seems to work up to Larafvel 9.22 now with Laravel 9.25 I am getting composer error again.

**Comment by arkaitzgarro** [comment]
> So we tried the BETA tag and it seems to work up to Larafvel 9.22 now with Laravel 9.25 I am getting composer error again.

Can you share the specific error you are seeing?

**Comment by arkaitzgarro** [comment]
> So we tried the BETA tag and it seems to work up to Larafvel 9.22 now with Laravel 9.25 I am getting composer error again.

I installed the beta in a project with Laravel 9.34, and so far so good, no errors when installing the package.

**Comment by snake-py** [comment]
@arkaitzgarro oh I forgot to answer. Yes the issues we have seen did not relate to this package. Sorry for the false alarm
