### ISSUE TITLE
Transaction not getting associated with Errors on Elastic Cloud APM

### ISSUE THREAD

**Issue by abhishek1234graphs** [arkaitzgarro/elastic-apm-laravel#164]
If you notice the latest intake/v2/events Error schema on https://www.elastic.co/guide/en/apm/guide/current/api-error.html, along with the `transaction_id`, a `transaction` object should also be present in the incoming JSON. 
Now in `jsonSerialize` function of `Nipwaayoni\Events\Error`, the `transaction` key is not present. Therefore this key is never included during API calls made to Elastic Cloud APM Server.
I called the API with and without the `transaction` key - the resulting Error (captured using `captureThrowable` function) got associated with a Transaction only if this key is included in the request body. Without the inclusion of this key, the Transaction correctly displays the presence of an Error, but never really redirects to the Error upon trying to inspect the associated Error separately (when you click on "View related error" on the Transaction).
Is it possible for you to upgrade `Nipwaayoni\Events\Error` to appropriately include this new Schema?

**Comment by arkaitzgarro** [comment]
Hi @abhishek1234graphs,

Thanks for the report. Can you open this issue in https://github.com/nipwaayoni/elastic-apm-php-agent repository, or even create a PR to fix the issue? We don't own the package, and the moment it's fixed, this library will immediately benefit from it.
