### ISSUE TITLE
Send only Transactions associated with Exceptions to APM Server

### ISSUE THREAD

**Issue by abhishek1234graphs** [arkaitzgarro/elastic-apm-laravel#165]
This issue is more of an enhancement-request.
Inside `AG\ElasticApmLaravel\ServiceProvider::registerAgent()`,currently all Transactions are getting sent to an APM server. I understand that this dispatch to the APM server can be completely disabled or enabled on the basis of an environment variable.

Our requirement is to send only Transactions that result in Exceptions. Inside our Exceptions handler, we successfully capture the thrown Exceptions using the `captureThrowable()` function. Is it possible to probably add a global identifier during the application execution which, if set properly, can determine whether or not to send the Transaction to the APM Server? We intend to modify this global identifier on-the-fly during the application's execution. 

As a work around, we have placed this package in a separate folder and we have modified the `registerAgent` function as follows:

```
$this->app->terminating(function (Request $request, Response $response) {
            /** @var Agent $agent */
            $agent = $this->app->make(Agent::class);

            global $doesErrorExist;

            if($doesErrorExist === true){
                $agent->send();    
            }
            
        });
```

**Comment by countless-integers** [comment]
We're open to PRs, but you need to find a configurable solution (opt-out by default) that doesn't include a global variable, because those are way to confusing to debug.
