### ISSUE TITLE
Need to include latest version of nipwaayoni/elastic-apm-php-agent

### ISSUE THREAD

**Issue by abhishek1234graphs** [arkaitzgarro/elastic-apm-laravel#168]
Using the previous versions of `nipwaayoni/elastic-apm-php-agent`, we noticed that Transactions were not getting correlated with Errors in Elastic Cloud APM. We alerted the package owners here: https://github.com/nipwaayoni/elastic-apm-php-agent/issues/78

In the latest version of `nipwaayoni/elastic-apm-php-agent`, this issue has been fixed. The problem is that your package relies on `"nipwaayoni/elastic-apm-php-agent": "^7.5"`, which is not the latest version i.e. `version 8.0.0`.
Is it possible for you to please include the latest version of `nipwaayoni/elastic-apm-php-agent` in your `composer.json` so that Transactions get associated with Errors accurately?

**Comment by arkaitzgarro** [comment]
Dependabot created a [PR already](https://github.com/arkaitzgarro/elastic-apm-laravel/pull/167), let me quickly check everything is ok

**Comment by arkaitzgarro** [comment]
Version `v3.1.0` includes the latest changes from `nipwaayoni/elastic-apm-php-agent`
