### ISSUE TITLE
AG\ElasticApmLaravel\Collectors\EventDataCollector::shouldIgnoreTransaction(): Argument #1 ($transaction_name) must be of type string,

### ISSUE THREAD

**Issue by tomvo** [arkaitzgarro/elastic-apm-laravel#171]
```
Php version: 8.1
Package version: v4.0.0
```

I just (re)implemented the package and getting the following exception:

```
TypeError: AG\ElasticApmLaravel\Collectors\EventDataCollector::shouldIgnoreTransaction(): Argument #1 ($transaction_name) must be of type string, null given, called in /data/www/freeontour.com/test/releases/45/vendor/arkaitzgarro/elastic-apm-laravel/src/Collectors/ScheduledTaskCollector.php on line 96
Error
```

Any idea?

**Comment by arkaitzgarro** [comment]
Do you have an example of how do you schedule tasks? I have the impression we expect a command, but Laravel allows more than that.

**Comment by tomvo** [comment]
We have quite a bit of scheduled tasks. 

The normal ones in console/Kernel.php like:

```
$schedule->command('...')->everyFiveMinutes();
```
and

```
 $schedule->job(new MyJob)->dailyAt('07:00');
 ```
 
 but also in different Service Providers like this:

```
public function boot(): void
    {
            //Register the clean cached command to be scheduled hourly
            $this->app->booted(function () {
                $schedule = $this->app->make(Schedule::class);

                $schedule->command('...')->daily();
            });
    }
```

I tried to debug the exception but i cannot seem to trigger it manually.

**Comment by tomvo** [comment]
hey @arkaitzgarro  any chance we can look into this, if you need any more input from my side let me know. I'm getting this basically on every single piece of code i execute in our test environment.

**Comment by arkaitzgarro** [comment]
Hi @tomvo, I can reproduce locally, looks like the problem is both with scheduling closures or invokable objects, where we cannot infer the name of the task. I'll work on a fix an keep you posted.

**Comment by tomvo** [comment]
Awesome, let me know if you want me to do some further testing!

**Comment by arkaitzgarro** [comment]
@tomvo a new version `v4.0.1` has been released, and it should include a fix for this problem. Let me know if it is fixed for you.
