### ISSUE TITLE
Laravel Telescope Support

### ISSUE THREAD

**Issue by nasrulhazim** [arkaitzgarro/elastic-apm-laravel#173]
Hi @arkaitzgarro , i am just wondering if it's a good idea to utilise [Laravel Telescope](https://laravel.com/docs/9.x/telescope) since they already collecting all kind of Laravel features.

I think from Telescope, we just need to add another storage for Elastic APM. 

I've been think quite sometimes how I can utilise Laravel Telescope into Elastic.

Let me know if it's possible, and if there's a way I can contribute to this package, or create another package for Telescope, Elastic APM driver.

**Comment by arkaitzgarro** [comment]
Hey @nasrulhazim, maybe I'm missing something, but I see Telescope and APM as very different services, and I don't know how this package can help any of them.

If anything, we could get inspired by Telescope to add more features or metadata to this package.
