### ISSUE TITLE
Is there a reason that this agent doesn't allow collecting stacktraces?

### ISSUE THREAD

**Issue by kvas-damian** [arkaitzgarro/elastic-apm-laravel#176]
First of all, thanks for your work on this repo. We successfully migrated from https://github.com/philkra/elastic-apm-laravel and we love possibility to register our own collectors (DB transactions, Redis, HTTP requests and others).

The only feature that we're missing from the previous APM integration is lack of stacktraces. In APM stacktraces looks as on screenshot and allows us to easily trace the source of the Span
![Zrzut ekranu 2023-10-11 o 10 00 24](https://github.com/arkaitzgarro/elastic-apm-laravel/assets/2725894/c78030e2-3880-4553-84f3-6d68322a989f)

I found a method that allows us to [set stacktraces on Span in APM agent](https://github.com/nipwaayoni/elastic-apm-php-agent/blob/47c814902449738131c0bd4e457ffef5d8a58718/src/Events/Span.php#L162), so it should be fairly easy to pass it through [Agent](https://github.com/arkaitzgarro/elastic-apm-laravel/blob/master/src/Agent.php#L101-L116)

Summarizing, the question is: Is it intended that this Agent doesn't allow to record spans with stacktraces?

**Comment by arkaitzgarro** [comment]
Hey @kvas-damian ,

No specific reason we didn't implement stacktraces, we were focused on implementing other features I guess. I could take a look in a few weeks, but feel free to open a PR if you think you can make it work :)

**Comment by kvas-damian** [comment]
@arkaitzgarro  please take a look on #177
