### ISSUE TITLE
Add protection in startMeasure if it is already started

### ISSUE THREAD

**Issue by cykirsch** [arkaitzgarro/elastic-apm-laravel#19]
Likely in `TimelineDataCollector`. I think an exception might be extreme but a log could helpful. Potentially:

```
    public function startMeasure(
        string $name,
        string $type = 'request',
        string $action = null,
        string $label = null,
        float $start_time = null
    ): void {
        if ($this->hasStartedMeasure($name) {
            // Throw Exception?
            // Log Warning?
            return;
        }

        $start = $start_time ?? microtime(true);
        $this->started_measures->put($name, [
            'label' => $label ?: $name,
            'start' => $start - $this->request_start_time,
            'type' => $type,
            'action' => $action,
        ]);
    }
```

**Comment by arkaitzgarro** [comment]
I also think that throwing an exception is a bit excessive, you don't want your application to crash because you called two events with the name name. Log a waring should be enough for both `startMeasure` and `stopMeasure`.

**Comment by cykirsch** [comment]
In `stopMeasure`, are you suggesting to replace the exception that's there with a warning and `return;`?

**Comment by arkaitzgarro** [comment]
I think we should follow the same pattern in both methods yes.
