### ISSUE TITLE
Extendable collectors

### ISSUE THREAD

**Issue by cykirsch** [arkaitzgarro/elastic-apm-laravel#20]
My core issue is that I want to hook into the agent to track jobs. My preferred solution is #18, but I'm also ok with #11. 

But if not that, then there are a couple things I think should be done to allow better extensibility:

1. Split up HttpCollector so the framework stuff is done in its own collector. See the above PRs for a sample FrameworkCollector implementation. This is needed so that when I add my own collector for jobs, it doesn't have a "Route matching" span that never ends. I supposed you could just go with the `isHttpRequest` to not start the route_matching but I do think it's a bit awkward to have the boot stuff in http--may be just me
2. Since the Agent is a singleton, I can pick that up anywhere, but since `$collectors` isn't public, I can't just add my own. Either a `getCollectors` method or a public property would be fine.

Even if one of my job PRs is merged, step 2 may still be useful.

**Comment by arkaitzgarro** [comment]
Both of them are great ideas. 
1. Will split the responsibilities collector and avoid the issues that you mentioned with jobs. We should do it regardless of the PRs you opened.
2. What about adding an `addCollector()` method instead? It would be a nicer API for the user. Something like:
```php
$agent->addCollector(MyCollector::class);
```

**Comment by cykirsch** [comment]
1. If I'm reading into the situation right, it seems you're leaning toward #18 so this will get taken care of there.
2. I like that! PR incoming, but I'm thinking it should wait for jobs and get cleaned up before then.
