### ISSUE TITLE
Package collaboration

### ISSUE THREAD

**Issue by dstepe** [arkaitzgarro/elastic-apm-laravel#52]
Greetings! I see that you use the `philkra/elastic-apm-php-agent` package to provide the underlying APM service. That package has been seen much activity, and by mutual agreement with the author, I have created a replacement package to continue development (https://github.com/nipwaayoni/elastic-apm-php-agent). Philkra also published a Laravel APM package based on his Agent which I picked up as well (https://github.com/nipwaayoni/elastic-apm-laravel).

Would you consider switching to the new Agent package? There are some breaking changes to deal with, but I'm trying to keep improving it while watching the official Elastic APM Agent for PHP (https://github.com/elastic/apm-agent-php). I'd be happy to get feedback to benefit your Laravel package as well as the Agent.

I'd also like to consider how we might consolidate the Laravel APM packages. I like what I see in your implementation and I believe the community would benefit from collaboration.

I open to discussion.

**Comment by arkaitzgarro** [comment]
Hey @dstepe 
> I see that you use the `philkra/elastic-apm-php-agent` package to provide the underlying APM service. That package has been seen much activity, and by mutual agreement with the author, I have created a replacement package to continue development (https://github.com/nipwaayoni/elastic-apm-php-agent). Philkra also published a Laravel APM package based on his Agent which I picked up as well (https://github.com/nipwaayoni/elastic-apm-laravel).
> 
> Would you consider switching to the new Agent package? There are some breaking changes to deal with, but I'm trying to keep improving it while watching the official Elastic APM Agent for PHP (https://github.com/elastic/apm-agent-php). I'd be happy to get feedback to benefit your Laravel package as well as the Agent.

Yes, I'm aware of both the package that you are maintaining now and also the official work done by Elastic. Ideally, I would like to wait for the official package, otherwise, we will need to perform to migrations. But we could move to your implementation if you can help us with the migration of course. Which features do include that are not part of Philkra package?

> I'd also like to consider how we might consolidate the Laravel APM packages. I like what I see in your implementation and I believe the community would benefit from collaboration.

Do you already have something in mind? Like moving this package to nipwaayoni organization?

**Comment by dstepe** [comment]
My apologies for failing to respond sooner. Life happens.

I had two reasons for my offer. First, there are some known issues with the `philkra/elastic-apm-php-agent` package which we have tried to address in the new package. We've also add some requested features. With the work starting up on the official package, I don't plan to put much more effort into this ours, but I hope it can act as a bridge until the official package is ready. 

Second, I don't see a lot of value in maintaining the Laravel package inherited from philkra if we can achieve better outcomes by putting energy into yours. (I'm not suggesting moving your package, btw, unless you having it a GitHub organization is beneficial to you.)

I'd be interested in working with you to switch to the updated agent and collaborating on any changes that would provide improvements to your Laravel package. At the same time, I may have features to contribute to your package based on my needs for APM in Laravel.

**Comment by arkaitzgarro** [comment]
> I had two reasons for my offer. First, there are some known issues with the `philkra/elastic-apm-php-agent` package which we have tried to address in the new package. We've also add some requested features. With the work starting up on the official package, I don't plan to put much more effort into this ours, but I hope it can act as a bridge until the official package is ready.

It sounds like a good idea. We are using `dev-master` version from `philkra/elastic-apm-php-agent` which is far from ideal, and even had to override some parts to make it work as expected. I could create a PR with your package and ask for help if necessary.

> Second, I don't see a lot of value in maintaining the Laravel package inherited from philkra if we can achieve better outcomes by putting energy into yours. (I'm not suggesting moving your package, btw, unless you having it a GitHub organization is beneficial to you.)
> 
> I'd be interested in working with you to switch to the updated agent and collaborating on any changes that would provide improvements to your Laravel package. At the same time, I may have features to contribute to your package based on my needs for APM in Laravel.

I'm fine keeping the Laravel package in my account for now. We use it on our production applications, it's quite critical for us to keep it working :) Please create some issues/PRs with your needs, and we can discuss them.

**Comment by dstepe** [comment]
@arkaitzgarro I'm looking at the branch you started to switch packages and see that the work I did to around agent construction and configuration makes it difficult to extend the `Agent` class as you are doing. I think I can address this shortcoming in the `AgentBuilder`.

I've forked your repo and will work on this.
