### ISSUE TITLE
Is this compatable with PHP 7.2?

### ISSUE THREAD

**Issue by deokgonkim** [arkaitzgarro/elastic-apm-laravel#55]
My environment
PHP 7.2 (docker php:7.2-fpm)
laravel/framework: 5.7.*

**Comment by arkaitzgarro** [comment]
Hi @deokgonkim , unfortunately this package is only compatible with PHP `>= 7.3`. Support for version 7.2 ended on 30 Nov 2019, and it's only getting security updates until 30 Nov 2020. We decided to go for 7.3 as it has longer support.
