### ISSUE TITLE
On-the-fly enable

### ISSUE THREAD

**Issue by cykirsch** [arkaitzgarro/elastic-apm-laravel#69]
We're interested in having APM only send events 10% of the time, and handling this via feature flags. https://github.com/checkr/flagr if you're curious.

I'm curious what you think about how to approach this. We could make our own custom service provider that extends yours, in order to make a flagr request prior to reading the provided configuration option. Do you see a clean way we could provide the ability to hook into the library instead of making a custom service provider?

**Comment by cykirsch** [comment]
We use `php artisan cache` at deploy time so we can't do it inside the config file.

**Comment by dstepe** [comment]
To clarify, are you interested in sending a specific 10% or simply a random 10% of the transaction events? I'm not sure how a feature flag would accomplish this.

I believe this is actually a needed enhancement of of the underlying APM Agent. I've suggested to the author of this package that we switch to an alternate release, and transaction sampling rate is already a requested feature enhancement:

https://github.com/nipwaayoni/elastic-apm-php-agent/issues/22

Is that what you are looking for?

**Comment by cykirsch** [comment]
That's great information, thank you for sharing. Ideally that feature is exactly what we'd want, but without it actually being implemented we are stuck with the same as what you mentioned--just override `active` event though it is not optimal.

**Comment by dstepe** [comment]
I believe you could extend `AG\ElasticApmLaravel\Agent` class and override the `send()` method. Then add condition which only calls `parent::send()` based on your given transaction sampling rate. I have not tried this, but I don't see why it would not work.

There are caveats, however. The Agent class does not currently expose any functionality to clear its collected events. That's done as part of calling `send()` and would therefore not happen when non-sampled transactions. If you have long running PHP processes which handle multiple transactions, this would result in all events being sent, but in batches.

Second, exception events would also only be sent based on your sampling rate, which may lead to undercounting or even missing exceptions. That's not n% of exceptions, it's n% of all events, which would make it easy to miss exceptions.

These are types of issues I would expect a proper feature in the underlying package to address, but if your primary concern is simply reduce the overall sampling, this simple solution may suffice for now.

**Comment by dstepe** [comment]
I should also point out that the Python agent referred to in that issue implements sampling a little differently than what I suggested would achieve:

> By default, the agent will sample every transaction (e.g. request to your service). To reduce overhead and storage requirements, you can set the sample rate to a value between 0.0 and 1.0. We still record overall time and the result for unsampled transactions, but no context information, labels, or spans.

https://github.com/elastic/apm-agent-python/blob/master/docs/configuration.asciidoc#transaction_sample_rate

The key difference being that all transactions are counted and timed, but only the sampled ones contain context data. I'm not sure if there is an official standard for transaction sampling, but I'll look into that before adding it to the Agent package.

**Comment by arkaitzgarro** [comment]
I agree with @dstepe on all his points:
- A simple way to implement throttling is overriding the Agent's `send` method, and add a conditional like `if (rand(0, 100) > $ff) return`. This could lead to some unexpected data being sent for jobs.
- I think you remember the [`shouldIgnoreTransaction`](https://github.com/arkaitzgarro/elastic-apm-laravel/blob/master/src/Collectors/JobCollector.php#L121) implemented in both the Middleware and the JobCollector. You could instead override these methods to add the condition there, as this will prevent transactions to be created and data to be collected.

But indeed, I think this should be a feature that the underlying PHP agent should implement, so everyone can benefit from it.

**Comment by dstepe** [comment]
I intend to make the transaction sampling rate the next feature I implement in the agent package. I'll start on that when we have completed (or nearly completed) switching this package over to use the new agent.

**Comment by cykirsch** [comment]
I put up a PR that helps with the configuration aspect, they are generic changes that just pull the config out into its own service. Please let me know what you think of the changes.

I was thinking the `shouldIgnoreTransaction` was going to have the same not-clearing-collected-events problem but as I looked at it again it does seem like it should work the way you suggest @arkaitzgarro.

I'm glad to hear sampling will be high on the list for the agent @dstepe, that's going to be extremely useful!

**Comment by cykirsch** [comment]
FWIW I'm in favor of counting all transactions/errors but only including the details on the sample
