### ISSUE TITLE
Max trace items is applied per collector rather than to total events

### ISSUE THREAD

**Issue by dstepe** [arkaitzgarro/elastic-apm-laravel#85]
While writing unit tests for the `Agent` class, I found that the max trace items setting is used to take that number of items from each collector:

https://github.com/arkaitzgarro/elastic-apm-laravel/blob/master/src/Agent.php#L70

The README defines max trace items as "Max number of child items displayed when viewing trace details" which is not consistent with the implementation.

Should the implementation be fixed or should the documentation be updated to reflect this is per collector? I vote for fixing the implementation, but makes the behavior rather arbitrary since you make take all of one type and none of another based purely on which collector is processed first.

A better solution might be to create a global `EventCollectionTracker` object which all collectors refer to and increment each time they collect an event. Each collector will then ask that object if it should collect an event and discard the event if not. Only that tracker object would need to be concerned with the max trace items, and the collectors would not consume memory collecting events which won't actually be pushed to APM.

Given that the default is 1000 items, it may be unlikely that anyone ever hits this problem, so maybe it's low priority.

**Comment by arkaitzgarro** [comment]
I think we should fix the implementation indeed. I like the idea of having a global counter to avoid collecting events that we will discard later on, and since all measurements are centralised in `EventDataCollector` class, we can easily discard events once the user reaches the limit.

What do you think about also implementing this limit in the PHP Agent? Is not as performant as not collecting events, but will solve this problem for every implementation.

**Comment by dstepe** [comment]
I agree with fixing the implementation as described. I assume this is not a high priority, though, or someone would have raised the issue by now. So maybe this waits for the next minor release while we finish the current work.

I do plan to make significant changes to the event tracking in the agent package as a next major release. This problem would be one that could be addressed.

**Comment by cykirsch** [comment]
This is great. We do hit the limit frequently on one of our APIs. I hadn't dug into how to fix but did notice that _everything_ is collected and not limited until later, so there's a memory benefit for sure.
